blog/urls.py
from django.urls import path

from . import views


app_name = "blog"

urlpatterns = [
    # ex: /blog/
    path('', views.ArticleListView.as_view(), name='index'),
    path('article/<slug:slug>/', views.ArticleDetailView.as_view(), name='article'),
    path('category/<slug:slug>/', views.CategoryView.as_view(), name='category'),
    path('tag/<slug:slug>/', views.TagView.as_view(), name='tag'),
    path('archive', views.ArchiveView.as_view(), name='archive'),
]

oauth/urls.py
from django.urls import path

from . import views


app_name = "oauth"

urlpatterns = [
    path('oauth_login', views.oauth_login, name='oauth_login'),
    path('oauth_logout', views.oauth_logout, name='oauth_logout'),
    path('authorize', views.authorize, name='authorize'),
]

simpleblog/urls.py
from django.contrib import admin
from django.urls import path, include

from haystack.views import SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oauth/', include('oauth.urls')),
    path('', include('blog.urls')),
    path('search/', SearchView(), name='haystack_search'),
    path('comment/', include('comment.urls')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load blog_tags %}
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="xShen's Blog">
    {% block header %}
        <meta name="description" content="xShen's Blog">
        <meta name="keywords" content="Python,Django,JavaScript,Linux,Docker,K8S,Zabbix,Nagios,Ansible,Jenkins">
        <title>xShen's Blog</title>
    {% endblock %}
    <link rel="icon" href="../../favicon.ico">
    <!-- Load stylesheet -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/fonts.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/blog.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/comment.css' %}" />
    {% block specificcss %}
    {% endblock %}
</head>
<body class="components hasnavbar"
      data-spy="scroll"
      data-target=".dynamic-nav"
      data-offset="100">
    <!-- Navbar -->
    <nav class="navbar navbar-inverse">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-docs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand site-name" href="/">xShen's Blog</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div id="bs-docs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="/">关于</a></li>
                    <li><a href="{% url 'blog:archive' %}">归档</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <form class="navbar-form" action="/search" method="get">
                            <div class="form-group inner-addon left-addon">
                                <span class="glyphicon glyphicon-search" id="icon-search"></span>
                                <input type="text" class="form-control search" placeholder="Search" name="q" autocomplete="off" style="width: 200px;">
                            </div>
                        </form>
                    </li>
                    {% if user.username %}
                        <li>
                            <div class="uavatar">
                                <img src="{{ user.oauthuser.profile_image_url }}"></img>
                            </div>
                        </li>
                        <li><p class="navbar-text">{{ user.oauthuser.nickname }}</p></li>
                        <li><a href="{% url 'oauth:oauth_logout' %}">退出</a></li>
                    {% else %}
                        <li><a href="{% url 'oauth:oauth_login' %}?next_url={{ request.get_full_path }}">登录</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-3">
                {% block articlemenu %}
                {% endblock %}
                <div class="row">
                    <div class="col-md-12">  
                        <div class="widget">
                            <div class="widget-title">
                                <span>分类</span>
                            </div>
                            <div class="widget-body">
                                <div>{% load_category %}</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="widget">
                            <div class="widget-title">
                                <span>标签</span>
                            </div>
                            <div class="widget-body">
                                <div>{% load_tag %}</div>
                            </div>   
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="text-center footer-text">
                        Copyright &copy; 2019 xShen's Blog<br>Powered by <a href="https://github.com/xshen1898/SimpleBlog">SimpleBlog</a> on 阿里云
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <a class="scroll-to-top"><span class="glyphicon glyphicon-chevron-up"></span></a>
    <!-- Include Javascript libraries at the end of the html body. -->
    <script src="{% static 'js/jquery-1.12.4.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/blog.js' %}"></script>
    <script src="{% static 'js/comment.js' %}"></script>
    {% block specificjs %}
    {% endblock %}
</body>
</html>